### ISSUE TITLE
Yandex Mapkit help

### ISSUE THREAD

**Issue by aspi632** [sandino/Markdown-Cheatsheet#2]
Здравствуйте!
Я начинающий андроид программист и пытаюсь разобраться в Яндекс Мапките, а именно - хочу реализовать рисование поверх карты (как, например, в приложении Циан) с последующим выделением placemark'ов внутри нарисованной области.
Копаясь в официальном гитхабе, нашёл Ваше сообщение https://github.com/yandex/mapkit-android-demo/issues/111 , из чего сделал вывод, что работали над схожей задачей)
Не могли бы вы поделиться кодом, если это не затруднит Вас и не составляет коммерческой интеллектуальной собственности
В любом случае, спасибо за ответ!
С уважением, Александр

**Comment by jajamorgan** [comment]
xD
